	LJMP	START
	ORG	100H
START:
	LCALL	WAIT_KEY	;POBIERZ KOD 1 KLAWISZA
	MOV	R0,A		;ZAPISZ KOD W R0
	LCALL	WAIT_KEY	;POBIERZ KOD 2 KLAWISZA
	MOV	R1,A		;ZAPISZ KOD W R1
	LCALL	WAIT_KEY	;POBIERZ KOD 3 KLAWISZA
	CJNE	R0,R1,L1	;PORÓWNAJ KODY KLAWISZY 1 z 2, JEŒLI 2 JEST WIÊKSZY USTAW C=1, JEŒLI NIE C=0, PO USTAWIENIU KONTYNUUJ
L1:
	JC	L2		;JEŒLI KOD 2 BY£ WIÊKSZY TO SKOCZ DO L2, JEŒLI NIE TO KONTYNUUJ
	CJNE	R0,A,L5		;PORÓWNAJ KODY KLAWISZY 1 z 3, JEŒLI 3 JEST WIÊKSZY USTAW C=1, JEŒLI NIE C=0, PO USTAWIENIU KONTYNUUJ

L5:
	JC	L4		;JEŒLI KOD 3 BY£ WIÊKSZY TO SKOCZ DO L4, JEŒLI NIE TO KONTYNUUJ
	MOV	R3,#1		;KOD 1 BY£ NAJWIÊKSZY ZATEM USTAW R3=1
	SJMP	L6		;SKOCZ DO L6

L2:
	CJNE	R1,A,L3		;PORÓWNAJ KODY KLAWISZY 2 z 3, JEŒLI 3 JEST WIÊKSZY USTAW C=1, JEŒLI NIE C=0, PO USTAWIENIU KONTYNUUJ

L3:
	JC	L4		;JEŒLI KOD 3 BY£ WIÊKSZY TO SKOCZ DO L4, JEŒLI NIE KONTYNUUJ
	MOV	R3,#2		;KOD 2 BY£ NAJWIÊKSZY ZATEM USTAW R3=2
	SJMP	L6		;SKOCZ DO L6

L4:
	MOV	R3,#3		;KOD 3 BY£ NAJWIÊKSZY ZATEM USTAW R3=3

L6:
	CPL	P1.7		;ZAPAL DIODE
	MOV	A,#10		;CZEKAJ
	LCALL	DELAY_100MS	;WCI¥¯
	CPL	P1.7		;ZGAŒ DIODÊ
	MOV	A,#10		;CZEKAJ
	LCALL	DELAY_100MS	;WCI¥¯
	DEC	R3		;ZMNIEJSZ WARTOŒÆ R3
	CJNE	R3,#0,L6	;JEŒLI S¥ RÓWNE KONTYNUUJ, JEŒLI NIE PÊTLA WYWO£A SAM¥ SIEBIE
	SJMP	START		;POWRÓT DO POCZ¥TKU

