	LJMP	START
	ORG	100H
START:
	LCALL	WAIT_KEY	;POBIERANIE KODU KLAWISZA
	MOV	R0,A		;PRZYPISANIE KODU KLAWISZA DO R0
	MOV	R1,A		;PRZYPISANIE KODU KLAWISZA DO R1
	CJNE	R0,#0,START	;JEŒLI KOD KLAWISZA JEST RÓWNY 0 SKOCZ DO START
L1:
	MOV	A,#30		;D£UGA PRZERWA
	LCALL	DELAY_100MS	;POMIÊDZY D£UGIMI SEKWENCJAMI
	SJMP	L3		;SKOCZ DO L3 (PÊTLA KRÓTKICH SEKWENCJI)
	
L2:
	DEC	R0		;ZMNIEJSZ R0
	CJNE	R0,#0,L1	;JEŒLI R0 JEST RÓWNE 0 TO NIE WYKONUJ SKOKU, JEŒLI RÓ¯NE TO PÊTLA WYWO£UJE SAM¥ SIEBIE
	SJMP	START		;POWRÓT DO POCZ¥TKU

L3:
	CPL	P1.7		;ZAPAL DIODÊ
	MOV	A,#10		;POCZEKAJ
	LCALL	DELAY_100MS	;WCI¥¯ POCZEKAJ
	CPL	P1.7		;ZGAŒ DIODÊ
	MOV	A,#10		;POCZEKAJ
	LCALL	DELAY_100MS	;WCI¥¯ POCZEKAJ
	DEC	R1		;ZMNIEJSZ R1
	CJNE	R1,#0,L3	;JEŒLI R1 JEST RÓWNE 0 TO NIE WYKONUJ SKOKU, JEŒLI RÓ¯NE TO PÊTLA WYWO£UJE SAM¥ SIEBIE
	SJMP	L2		;POWRÓT DO PÊTLI "DU¯EJ"