	LJMP	START
	ORG	100H
START:
	MOV	R0,#CSDS	;
	MOV	A,#00000001B	;AKTYWOWANIE KLAWISZA ENTER
	MOVX	@R0,A		;

	MOV	TMOD,#01010001B	;USTAWIENIE LICZNIKA I TIMERA
	MOV	TH1,#0		;WYZEROWANIE ST BITOW LICZNIKA
	MOV	TL0,#0		;WYZEROWANIE ML BITOW TIMERA

	MOV	TL1,#0		;WYZEROWANIE LICZNIKA
L1:
	MOV	TL1,#0		;WYZEROWANIE ML BITOW LICZNIKA
	SETB	TR1		;URUCHOMIENIE LICZNIKA
	LCALL	CZEKAJ		;WYWOLANIE FUNKCJI CZEKAJACEJ
	CLR	TR1		;WYLACZENIE LICZNIKA
	MOV	A,TL1		;PRZYPISANIE LICZNIKA DO A
	CJNE	A,#3,L2		;POROWNANIE LICZNIKA DO 3
L2:
	JNC	L3
	CPL	P1.7		;ZAPALENIE DIODY
	SJMP	STOP		;ZAKONCZENIE PROGRAMU
L3:
	SJMP	L1		;POWROT DO POCZATKU PROGRAMU

STOP:
	SJMP	STOP


CZEKAJ:
	MOV	R1,#20		
C1:
	MOV	TH0,#256-180	;USTAWIENIE WARTOSCI POCZATKOWEJ
	SETB	TR0		;WLACZENIE TIMERA
	JNB	TF0,$		;CZEKANIE NA PRZEPELNIENIE TIMERA
	CLR	TF0		;WYCZYSZCZENIE BITU PRZEPELNIENIA
	CLR	TR0		;WYLACZENIE TIMERA
	DJNZ	R1,C1		;20 * 50MS = 1S
	RET